# Используем лёгкий образ с Python 3.10
FROM python:3.10-slim

# Рабочая папка внутри контейнера
WORKDIR /app

# Сначала копируем только requirements.txt и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь ваш код
COPY . .

# Экспонируем порт 5000
EXPOSE 5000

# Окружение для Flask (необязательно, но удобно)
ENV FLASK_ENV=development
ENV FLASK_APP=app.py

# По умолчанию запускаем Python‑сервер
CMD ["python", "app.py"]
